# Generated by Django 3.0.8 on 2022-08-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_post_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='me',
            old_name='twitter',
            new_name='phone',
        ),
    ]
