# Generated by Django 3.0.8 on 2022-08-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20220802_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='me',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='me',
            name='bio',
        ),
        migrations.AddField(
            model_name='me',
            name='bio',
            field=models.ManyToManyField(to='base.Activity'),
        ),
    ]
