# Generated by Django 3.0.8 on 2022-08-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20220802_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='me',
            name='skills',
            field=models.ManyToManyField(to='base.Skill'),
        ),
    ]
