# Generated by Django 3.0.8 on 2022-08-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20220802_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('image', models.ImageField(default='assets/img/work-4.jpg', upload_to='images/project')),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='me',
            name='projects',
            field=models.ManyToManyField(to='base.Project'),
        ),
    ]
