# Generated by Django 3.0.8 on 2022-08-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20220802_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='/static/assets/img/work-4.jpg', upload_to='images/project'),
        ),
    ]
