# Generated by Django 3.0.8 on 2022-08-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20220804_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(to='base.Galerie'),
        ),
    ]
